variables:
  RUSTUP_CACHE_FOLDER: /home/vsts/.rustup

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: Cache@2
    inputs:
    key: 'rustup | "$(Agent.OS)" | package | Cargo.toml'
    path: $(RUSTUP_CACHE_FOLDER)
    restoreKeys: 'rustup | "$(AGENT.OS)"'
    displayName: Cache ~/.rustup
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
